import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type DumpField = {
  name: string;
  type: "array" | "boolean" | "map" | "object" | "string" | "uint16" | "uint32";
  keySet?: string;
  valueType?: string;
};

type Dump = {
  profiles: string[];
  customTlsClient: { fields: DumpField[] };
  h2Settings: string[];
  h3Settings: string[];
  supportedCurves: string[];
  supportedVersions: string[];
  supportedSignatureAlgorithms: string[];
  supportedDelegatedCredentialsAlgorithms: string[];
  kdfIds: string[];
  aeadIds: string[];
  certCompressionAlgos: string[];
  errorKinds: string[];
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generated = join(root, "packages/effect-tls-client/src/generated");
const bridge = process.env["TLS_CLIENT_BRIDGE_PATH"] || join(root, "bridge/bridge");
const check = process.argv.includes("--check");

const compare = (left: string, right: string): number => (left < right ? -1 : left > right ? 1 : 0);

const sortUnique = (values: ReadonlyArray<string>): string[] => [...new Set(values)].sort(compare);

const readDump = (): Dump => {
  let output: string;
  try {
    output = execFileSync(bridge, ["dump"], { encoding: "utf8" });
  } catch (cause) {
    throw new Error(`failed to run ${bridge} dump`, { cause });
  }
  const value = JSON.parse(output) as Dump;
  if (!Array.isArray(value.profiles) || !value.customTlsClient?.fields) {
    throw new Error("Bridge dump is missing profile metadata");
  }
  return value;
};

const literalValues = (values: ReadonlyArray<string>): string => {
  const sorted = sortUnique(values);
  if (sorted.length === 0) throw new Error("Bridge dump contains an empty enum");
  return `[${sorted.map((value) => JSON.stringify(value)).join(", ")}] as const`;
};

const literals = (name: string, values: ReadonlyArray<string>): string =>
  `export const ${name}Values = ${literalValues(values)};\nexport const ${name} = Schema.Literals(${name}Values);`;

const typeUnion = (values: ReadonlyArray<string>): string =>
  sortUnique(values)
    .map((value) => JSON.stringify(value))
    .join(" | ");

const profileSource = (dump: Dump): string =>
  `// This file is generated by scripts/codegen.ts. Do not edit.\n\nimport { Schema } from "effect";\n\ntype KnownProfile = ${typeUnion(dump.profiles)};\nexport type Known = KnownProfile;\n\nexport namespace Profile {\n  export type Known = KnownProfile;\n}\n\nexport type Profile = Profile.Known | (string & {});\n\nexport const Profile = Schema.declare<Profile>(\n  (value): value is Profile => typeof value === "string",\n);\nexport const Known = Schema.Literals(${literalValues(dump.profiles)});\n\n${literals("H2Setting", dump.h2Settings)}\n${literals("H3Setting", dump.h3Settings)}\n${literals("SupportedCurve", dump.supportedCurves)}\n${literals("SupportedVersion", dump.supportedVersions)}\n${literals("SignatureAlgorithm", dump.supportedSignatureAlgorithms)}\n${literals("DelegatedCredentialsAlgorithm", dump.supportedDelegatedCredentialsAlgorithms)}\n${literals("KdfId", dump.kdfIds)}\n${literals("AeadId", dump.aeadIds)}\n${literals("CertCompressionAlgo", dump.certCompressionAlgos)}\n${literals("ErrorKind", dump.errorKinds)}\n`;

const keySchemas: Record<string, string> = {
  h2Settings: "H2Setting",
  h3Settings: "H3Setting",
};

const arraySchemas: Record<string, string> = {
  h2Settings: "H2Setting",
  h3Settings: "H3Setting",
  certCompressionAlgos: "CertCompressionAlgo",
  supportedCurves: "SupportedCurve",
  supportedDelegatedCredentialsAlgorithms: "DelegatedCredentialsAlgorithm",
  supportedSignatureAlgorithms: "SignatureAlgorithm",
  supportedVersions: "SupportedVersion",
};

const valueSchemas: Record<string, string> = {
  CandidateCipherSuiteMeta: "CandidateCipherSuite",
  PriorityFrameMeta: "PriorityFrame",
  string: "Schema.String",
  uint16: "UInt16",
  uint32: "UInt32",
};

const expectedFields: Record<string, DumpField["type"]> = {
  h2Settings: "map",
  h2SettingsOrder: "array",
  h3Settings: "map",
  h3SettingsOrder: "array",
  h3PseudoHeaderOrder: "array",
  headerPriority: "object",
  certCompressionAlgos: "array",
  ja3String: "string",
  keyShareCurves: "array",
  alpnProtocols: "array",
  alpsProtocols: "array",
  ECHCandidatePayloads: "array",
  ECHCandidateCipherSuites: "array",
  priorityFrames: "array",
  pseudoHeaderOrder: "array",
  supportedDelegatedCredentialsAlgorithms: "array",
  supportedSignatureAlgorithms: "array",
  supportedVersions: "array",
  connectionFlow: "uint32",
  recordSizeLimit: "uint16",
  streamId: "uint32",
  h3PriorityParam: "uint32",
  h3SendGreaseFrames: "boolean",
  allowHttp: "boolean",
};

const schemaForField = (field: DumpField): string => {
  switch (field.type) {
    case "map": {
      const key = field.keySet === undefined ? undefined : keySchemas[field.keySet];
      if (key === undefined || (field.valueType !== "uint32" && field.valueType !== "uint64")) {
        throw new Error(`unsupported map field ${field.name}`);
      }
      const keyValues = field.keySet === "h2Settings" ? "H2SettingValues" : "H3SettingValues";
      return `enumRecord(${keyValues}, ${field.valueType === "uint64" ? "NonNegativeInt" : "UInt32"})`;
    }
    case "array": {
      const element =
        field.keySet === undefined
          ? field.valueType === undefined
            ? undefined
            : valueSchemas[field.valueType]
          : arraySchemas[field.keySet];
      if (element === undefined) throw new Error(`unsupported array field ${field.name}`);
      return `Schema.Array(${element})`;
    }
    case "object":
      if (field.name !== "headerPriority")
        throw new Error(`unsupported object field ${field.name}`);
      return "PriorityParam";
    case "string":
      return "Schema.String";
    case "uint16":
      return "UInt16";
    case "uint32":
      return "UInt32";
    case "boolean":
      return "Schema.Boolean";
  }
};

const formatSource = (path: string, source: string): string =>
  execFileSync("bun", ["x", "oxfmt", "--stdin-filepath", path], {
    cwd: root,
    encoding: "utf8",
    input: source,
  });

const customProfileSource = (dump: Dump): string => {
  const fields = [...dump.customTlsClient.fields].sort((left, right) =>
    compare(left.name, right.name),
  );
  for (const field of fields) {
    if (expectedFields[field.name] !== field.type) {
      throw new Error(`Bridge dump custom profile field drift: ${field.name}`);
    }
  }
  const expected = Object.keys(expectedFields).sort();
  const actual = fields.map((field) => field.name).sort();
  if (expected.length !== actual.length || expected.some((name, index) => name !== actual[index])) {
    throw new Error("Bridge dump custom profile fields do not match the generator");
  }
  const properties = fields
    .map((field) => `  ${field.name}: Schema.optionalKey(${schemaForField(field)}),`)
    .join("\n");
  return `// This file is generated by scripts/codegen.ts. Do not edit.\n\nimport { Schema } from "effect";\nimport {\n  AeadId,\n  CertCompressionAlgo,\n  DelegatedCredentialsAlgorithm,\n  H2Setting,\n  H2SettingValues,\n  H3Setting,\n  H3SettingValues,\n  KdfId,\n  SignatureAlgorithm,\n  SupportedCurve,\n  SupportedVersion,\n} from "./Profile.js";\n\nconst NonNegativeInt = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0));\nconst UInt8 = NonNegativeInt.check(Schema.isLessThanOrEqualTo(0xff));\nconst UInt16 = NonNegativeInt.check(Schema.isLessThanOrEqualTo(0xffff));\nconst UInt32 = NonNegativeInt.check(Schema.isLessThanOrEqualTo(0xffffffff));\nconst enumRecord = <S extends Schema.Constraint>(values: ReadonlyArray<string>, value: S) =>\n  Schema.Record(Schema.String, value).check(\n    Schema.makeFilter(\n      (record) =>\n        Object.keys(record).every((key) => values.includes(key))\n          ? undefined\n          : { path: [], issue: "unknown enum value" },\n      { expected: "known enum value" },\n    ),\n  );\n\nexport const PriorityParam = Schema.Struct({\n  streamDep: UInt32,\n  exclusive: Schema.Boolean,\n  weight: UInt8,\n});\nexport interface PriorityParam extends Schema.Schema.Type<typeof PriorityParam> {}\n\nexport const PriorityFrame = Schema.Struct({\n  priorityParam: PriorityParam,\n  streamID: UInt32,\n});\nexport interface PriorityFrame extends Schema.Schema.Type<typeof PriorityFrame> {}\n\nexport const CandidateCipherSuite = Schema.Struct({\n  kdfId: KdfId,\n  aeadId: AeadId,\n});\nexport interface CandidateCipherSuite extends Schema.Schema.Type<typeof CandidateCipherSuite> {}\n\nexport const CustomProfile = Schema.Struct({\n${properties}\n});\nexport interface CustomProfile extends Schema.Schema.Type<typeof CustomProfile> {}\n`;
};

const dump = readDump();
const outputs = new Map<string, string>();
const profilePath = join(generated, "Profile.ts");
const customProfilePath = join(generated, "CustomProfile.ts");
outputs.set(profilePath, formatSource(profilePath, profileSource(dump)));
outputs.set(customProfilePath, formatSource(customProfilePath, customProfileSource(dump)));

for (const [path, content] of outputs) {
  let current: string | undefined;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = undefined;
  }
  if (check) {
    if (current !== content) {
      console.error(`generated file is stale: ${path}`);
      process.exitCode = 1;
    }
  } else if (current !== content) {
    writeFileSync(path, content);
  }
}
